name: 'Delete Docker Image'
description: 'Delete Docker Image from Registry'
inputs:
  image:
    description: 'Image name to delete'
    required: true
  tag:
    description: 'Tag to delete'
    required: true
  username:
    description: 'Docker Username'
    required: true
  password:
    description: 'Docker Password'
    required: true
  registry:
    description: 'Files to use to calculate the hash'
    required: false
    default: "https://hub.docker.com/v2"

runs:
  using: 'composite'
  steps:
    - id: calc
      shell: bash
      run: |
        registry=${{ inputs.registry }}
        name=${{ inputs.image }}
        tag=${{ inputs.tag }}

        echo "::notice:: Deleting Image ${name}:${tag}"

        TOKEN=$(curl \
            --silent \
            --header "Content-Type: application/json" \
            --request POST \
            --data '{"username": "'${{ inputs.username }}'", "password": "'${{ inputs.password }}'" }' \
            ${registry}/users/login/ \
            | jq -r .token)

        curl -X DELETE \
          --header "Authorization: JWT ${TOKEN}" \
          --header "Accept: application/json" \
          ${registry}/repositories/${name}/tags/${tag}
