# ref: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
name: 'Docker build'
description: 'Calculate deps and os hash'
inputs:
  image:
    description: "Image name to build and push"
    required: true
    type: string
    default: ${{ github.repository }}
  target:
    description: "Target Dockerfile Stage"
    type: string
  username:
    description: 'DockerHub username '
    required: false
  password:
    description: 'DockerHub password '
    required: false
  code_checksum:
    description: 'DockerHub password '
    required: false


defaults:
  run:
    shell: bash


outputs:
  image:
    description: 'Returns true if the image exists'
    value: ${{ steps.image_name.outputs.name }}
  version:
    description: 'Returns build number for the current branch'
    value: ${{ steps.meta.outputs.version }}
  created:
    description: 'Returns build number for the current branch'
    value: ${{ !steps.meta.image_status.updated }}


runs:
  using: 'composite'
  steps:
    - name: Cache regclient
      id: cache-regclient
      uses: actions/cache@v4
      with:
        path: $HOME/.regctl
        key: ${{ runner.os }}-regclient
    - name: Install regctl
      if: steps.cache-regclient.outputs.cache-hit != 'true'
      uses: regclient/actions/regctl-installer@main
    - name: DockerHub login
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - id: checksum
      uses: ./.github/actions/checksum

    - shell: bash
      id: env
      run: |
        build_date=$(date +"%Y-%m-%d %H:%M")
        echo "BUILD_DATE=$build_date" >> $GITHUB_ENV
        
        if [[ "${{inputs.target}}" == "dist" ]]; then
          echo "TAG_PREFIX=''" >> $GITHUB_ENV
        else
          echo "TAG_PREFIX=test-" >> $GITHUB_ENV
        fi
    - id: last_commit
      uses: ./.github/actions/last_commit
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ inputs.image }}
        flavor: |
          prefix=${{env.TAG_PREFIX}}
      env:
        DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
    - name: "Image Name"
      shell: bash
      id: image_name
      run: echo "name=${{ inputs.image }}:${{ steps.meta.outputs.version }}" >> $GITHUB_OUTPUT
    - name: "Check Image"
      id: image_status
      shell: bash
      run: |
        echo "::notice::ℹ Checking checksum for ${{ steps.image_name.outputs.name }}"
        image_checksum=$(regctl image inspect -p linux/amd64 \
                          --format '{{index .Config.Labels "checksum"}}' \
                          ${{ steps.image_name.outputs.name }} )
        code_checksum="${{ inputs.code_checksum }}"

        if [[ -z "$image_checksum"  ]]; then
          echo "::warning::🤔 No image checksum found"
          echo "updated=false" >> $GITHUB_OUTPUT
        elif [[ $image_checksum == $code_checksum ]]; then
          echo "::notice::😀 Image is updated"
          echo "updated=true" >> $GITHUB_OUTPUT
        else
          echo "::warning::🤬 Checksum: found '${image_checksum}' expected '${code_checksum}'"
          echo "updated=false" >> $GITHUB_OUTPUT
        fi
    - name: Set up Docker BuildX
      if: steps.image_status.outputs.updated != 'true' || contains(github.event.head_commit.message, 'ci:build')
      uses: docker/setup-buildx-action@v3.3.0
      with:
        platforms: linux/amd64
        driver: docker-container
        driver-opts: |
          image=moby/buildkit:v0.13.2
          network=host
    - name: Build and push
      if: steps.image_status.outputs.updated != 'true' || contains(github.event.head_commit.message, 'ci:build')
      id: build_push
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: "${{ steps.meta.outputs.labels }}\na=1\nb=2"
        annotations: "${{ steps.meta.outputs.annotations }}\nchecksum=${{ inputs.checksum }}"
        target: ${{ inputs.target }}
        file: ./docker/Dockerfile
        platforms: linux/amd64
        push: true
        sbom: true
        provenance: true
        cache-from: type=registry,ref=${{ inputs.image }}-cache
        cache-to: type=registry,ref=${{ inputs.image }}-cache,mode=max,image-manifest=true
        build-args: |
            GITHUB_SERVER_URL=${{ github.server_url }}
            GITHUB_REPOSITORY=${{ github.repository }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            CHECKSUM=${{ inputs.code_checksum }}
            VERSION=${{ steps.meta.outputs.version }}
            SOURCE_COMMIT=${{ steps.last_commit.outputs.last_commit_short_sha }}
