repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat
        args: ["--configuration", "djlint.toml"]

#  - repo: https://github.com/returntocorp/semgrep
#    rev: v1.141.0
#    hooks:
#      - id: semgrep
#        exclude: '(\.semgrep/|docs/)'
#        exclude_types:
#          - yaml
#        args:
#          - scan
#          - --config
#          - .semgrep/
#          # Do not try to scan '.semgrep/' directories as they contain test files
#          # thus they will trigger findings.
#          - --exclude=.semgrep/
#          - --exclude=docs/_scripts/
#          # Set the exit code to non-zero if there are findings.
#          - --error
#          # Do not check for version updates, it slows down the execution.
#          - --disable-version-check
#          # Quiet mode in order to not pollute the pre-commit outputs.
#          # Replace --quiet with --verbose to debug issues.
#          - --quiet

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.1
    hooks:
      - id: check-github-workflows
        args: [ "--verbose" ]

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.7.0"
    hooks:
      - id: tox-ini-fmt
        args: [ "-p", "lint" ]

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.11.0"
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff
      - id: ruff-format
        args:
          - --check
          - --config
          - ruff.toml

  - repo: https://github.com/saxix/pch
    rev: '0.2'
    hooks:

      - id: check-missed-migrations
        args:
          - src
        stages: [ pre-commit ]
        additional_dependencies: [ setuptools ]

      - id: check-untracked
        args:
          - src
          - tests
        stages: [ pre-push ]

      - id: check-forbidden
        args:
          - -i
          - "pyproject.toml"
          - -p
          - "/\\[tool.uv.sources\\]/"
        stages: [ pre-push ]

      - id: check-forbidden
        name: check pyproject to avoid editable sources/deps
        files: pyproject.toml
        language: python
        args:
          - -p
          - /\[tool\.uv\.sources\]\s/s
