[build-system]
build-backend = "hatchling.build"

requires = [ "hatchling" ]

[project]
name = "hope-dedup-engine"
version = "1.11.0"
description = "HOPE Deduplication Engine (HDE)"
readme = "README.md"
license = { text = "MIT" }

authors = [
  { name = "ddinicola" },
  { name = "Domenico DiNicola", email = "dom.dinicola@gmail.com" },
]
requires-python = ">=3.12,<3.13"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
]
dependencies = [
  "celery[redis]",
  "celery-types",
  "deepface",
  "django<7",
  "django-admin-extra-buttons",
  "django-adminactions",
  "django-adminfilters",
  "django-celery-beat",
  "django-celery-boost",
  "django-celery-results",
  "django-concurrency",
  "django-constance",
  "django-csp",
  "django-environ",
  "django-extensions",
  "django-filter",
  "django-flags",
  "django-regex",
  "django-smart-env",
  "django-storages[azure]",
  "django-svelte-jsoneditor",
  "djangorestframework",
  "dlib",
  "drf-nested-routers",
  "drf-spectacular[sidecar]",
  "flower",
  "mediapipe",
  "numpy<2",
  "psycopg[binary]",
  "psycopg-pool",
  "requests",
  "sentry-sdk[celery,django]",
  "setuptools",
  "social-auth-app-django",
  "social-auth-core",
  "tf-keras",
  "ultralytics",
  "unicef-security",
]

optional-dependencies.distribution = [
  "uwsgi",
]
optional-dependencies.docs = [
  "mkdocs",
  "mkdocs-awesome-pages-plugin",
  "mkdocs-gen-files",
  "mkdocs-material",
  "mkdocs-panzoom-plugin",
  "mkdocstrings-python",
]

[dependency-groups]
dev = [
  "black",
  "django-webtest",
  "factory-boy",
  "faker",
  "flake8",
  "flake8-bugbear",
  "flake8-formatter-junit-xml",
  "flake8-html",
  "freezegun",
  "graphene-stubs",
  "ipdb",
  "isort",
  "mypy",
  "openpyxl-stubs",
  "pdbpp",
  "pre-commit",
  "pytest",
  "pytest-celery",
  "pytest-cov",
  "pytest-django",
  "pytest-echo",
  "pytest-factoryboy",
  "pytest-mock",
  "pytest-xdist",
  "requests-mock",
  "responses",
  "ruff",
  "tox",
  "types-freezegun",
  "types-python-dateutil",
  "types-pytz",
  "types-redis",
  "types-requests",
  "unittest-xml-reporting",
  "watchdog",
]

[tool.hatch.build.targets.wheel]
packages = [ "src/hope_dedup_engine" ]

[tool.uv]
package = true

[tool.django-stubs]
django_settings_module = "hope_dedup_engine.config.settings"
