[tox]
requires =
    tox>=4.2
    tox-gh-actions
    tox-uv>=1.20.2
env_list =
    lint
    unit
    pkg_meta
skip_missing_interpreters = true

[testenv]
runner = uv-venv-lock-runner
pass_env =
    CACHE_URL
    CELERY_BROKER_URL
    DATABASE_URL
    STATIC_ROOT
    STATIC_URL
set_env =
    ADMIN_EMAIL = adm@test.com
    ADMIN_PASSWORD = testpassword
    ALLOWED_HOSTS = localhost,127.0.0.1
    AUTHENTICATION_BACKENDS =
    CELERY_TASK_ALWAYS_EAGER = True
    CRYPTOGRAPHY_DONT_BUILD_RUST = 1
    CSRF_COOKIE_SECURE = False
    DEBUG = False
    DEEPFACE_HOME = {envtmpdir}/.deepface
    DJANGO_ADMIN_URL = admin
    DJANGO_SETTINGS_MODULE = hope_dedup_engine.config.settings
    PYTHONPATH = .
    SECRET_KEY = versy-super-secret-test-key
commands =
    pytest {posargs}
dependency_groups = dev

[testenv:lint]
description = run static analysis and style check using ruff
skip_install = true
deps =
    pre-commit-uv>=4.1.1
pass_env =
    HOMEPATH
    PROGRAMDATA
commands =
    pre-commit run --all-files --show-diff-on-failure

[testenv:pkg_meta]
runner = uv-venv-lock-runner
description = check that the long description is valid
skip_install = true
commands =
    uv build -q --sdist --wheel --out-dir {envtmpdir}/dist .
    uvx twine check "{envtmpdir}/dist/*"
    uvx check-wheel-contents --ignore W001,W002,W004,W009 "{envtmpdir}/dist"
allowlist_externals =
    uv
    uvx
