# ref: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
name: 'Che cif image exists in dockerhub'
description: 'Calculate deps and os hash'
inputs:
  image:
    description: 'Docker Image '
    required: true
  username:
    description: 'DockerHub username '
    required: true
  password:
    description: 'DockerHub password '
    required: true

outputs:
  exists:
    description: 'The time we greeted you'
    value: ${{ steps.check.outputs.exixts }}

runs:
  using: 'composite'
#  args:
#    - ${{ inputs.files }}
  steps:
    - name: DockerHub login
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Check Image Exists
      id: check
      continue-on-error: true
      shell: bash --noprofile --norc -eo pipefail -ux {0}
      run: |
        set +e
        exists=$(docker manifest inspect ${{inputs.image}} > /dev/null 2>&1 && echo "exists" || echo "not_found")
        if [ $exists = "exists" ];then
          echo "exists=true" >> "$GITHUB_OUTPUT"
          echo "Image ${{inputs.image}} found"
        else
          echo "exists=false" >> "$GITHUB_OUTPUT"
          echo "Image ${{inputs.image}} does not exist"
        fi
