from hope_dedup_engine.apps.public_api.const import BULK_IMAGE_LIST, DEDUPLICATION_SET_LIST, IMAGE_LIST

DEDUPLICATION_SET_LIST_VIEW = f"{DEDUPLICATION_SET_LIST}-list"
DEDUPLICATION_SET_DETAIL_VIEW = f"{DEDUPLICATION_SET_LIST}-detail"
IMAGE_LIST_VIEW = f"{IMAGE_LIST}-list"
BULK_IMAGE_LIST_VIEW = f"{BULK_IMAGE_LIST}-list"
