# Generated by Django 5.0.6 on 2024-05-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeduplicationSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("reference_pk", models.IntegerField()),
                ("state", models.IntegerField(choices=[(0, "Clean"), (1, "Dirty"), (2, "Processing")], default=0)),
                ("deleted", models.BooleanField(default=False, verbose_name="deleted")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
            ],
        ),
        migrations.CreateModel(
            name="HDEToken",
            fields=[
                ("key", models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name="Key")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
            ],
            options={
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
                "abstract": False,
            },
        ),
    ]
