# Generated by Django 5.0.6 on 2024-05-17 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("public_api", "0001_initial"),
        ("security", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deduplicationset",
            name="created_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="deduplicationset",
            name="external_system",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="security.externalsystem"),
        ),
        migrations.AddField(
            model_name="hdetoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
