# Generated by Django 5.0.6 on 2024-05-24 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("security", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeduplicationSet",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("reference_pk", models.CharField(max_length=100)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Clean"), (1, "Dirty"), (2, "Processing"), (3, "Error")], default=0
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("error", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "external_system",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="security.externalsystem"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Duplicate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_reference_pk", models.CharField(max_length=100)),
                ("first_filename", models.CharField(max_length=255)),
                ("second_reference_pk", models.CharField(max_length=100)),
                ("second_filename", models.CharField(max_length=255)),
                ("score", models.FloatField()),
                (
                    "deduplication_set",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.deduplicationset"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HDEToken",
            fields=[
                ("key", models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name="Key")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("reference_pk", models.CharField(max_length=100)),
                ("filename", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deduplication_set",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.deduplicationset"),
                ),
            ],
        ),
    ]
