# Generated by Django 5.0.6 on 2024-07-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="duplicate",
            name="first_filename",
        ),
        migrations.RemoveField(
            model_name="duplicate",
            name="second_filename",
        ),
        migrations.AlterField(
            model_name="duplicate",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
