# Generated by Django 5.0.7 on 2024-09-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_duplicate_first_filename_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deduplicationset",
            name="error",
        ),
        migrations.AddField(
            model_name="deduplicationset",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True, unique=True
            ),
        ),
    ]
