# Generated by Django 5.0.6 on 2024-08-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_duplicate_first_filename_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deduplicationset",
            name="name",
        ),
    ]
