# Generated by Django 5.0.7 on 2024-09-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_config_deduplicationset_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deduplicationset",
            name="state",
            field=models.IntegerField(
                choices=[(0, "Clean"), (1, "Dirty"), (2, "Processing"), (3, "Error")],
                db_column="state",
                default=0,
            ),
        ),
        migrations.RenameField(
            model_name="deduplicationset",
            old_name="state",
            new_name="state_value",
        ),
    ]
