# Generated by Django 5.0.7 on 2024-09-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_deduplicationset_state_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IgnoredKeyPair",
            new_name="IgnoredReferencePkPair",
        ),
        migrations.RenameField(
            model_name="ignoredreferencepkpair",
            old_name="first_reference_pk",
            new_name="first",
        ),
        migrations.RenameField(
            model_name="ignoredreferencepkpair",
            old_name="second_reference_pk",
            new_name="second",
        ),
        migrations.AlterUniqueTogether(
            name="ignoredreferencepkpair",
            unique_together={("deduplication_set", "first", "second")},
        ),
    ]
