# Generated by Django 5.0.7 on 2024-09-25 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_ignoredkeypair_ignoredreferencepkpair_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgnoredFilenamePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=100)),
                ("second", models.CharField(max_length=100)),
                (
                    "deduplication_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.deduplicationset",
                    ),
                ),
            ],
            options={
                "unique_together": {("deduplication_set", "first", "second")},
            },
        ),
    ]
