# Generated by Django 5.0.7 on 2024-10-31 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_ignoredfilenamepair"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="config",
            name="face_distance_threshold",
        ),
        migrations.AddField(
            model_name="config",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="config",
            name="settings",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="config",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.config"),
        ),
    ]
