# Generated by Django 5.0.7 on 2024-10-30 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_ignoredfilenamepair"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="face_distance_threshold",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
