# Generated by Django 5.0.7 on 2024-10-30 12:45

import concurrency.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_config_face_distance_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="DedupJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.AutoIncVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "curr_async_result_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Current (active) AsyncResult is",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "last_async_result_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Latest executed AsyncResult is",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "celery_history",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                (
                    "celery_result",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "queue",
                    "terminate",
                    "inspect",
                    "revoke",
                ),
            },
        ),
    ]
