# Generated by Django 5.0.7 on 2024-11-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_dedupjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="dedupjob",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
