# Generated by Django 5.1.2 on 2024-11-05 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_dedupjob_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dedupjob",
            name="deduplication_set",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="api.deduplicationset"),
        ),
    ]
