# Generated by Django 5.1.2 on 2024-11-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_dedupjob_deduplication_set"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deduplicationset",
            name="state_value",
        ),
        migrations.AddField(
            model_name="deduplicationset",
            name="state",
            field=models.IntegerField(
                choices=[(0, "Clean"), (1, "Dirty")], db_column="state", default=0
            ),
        ),
    ]
