# Generated by Django 5.1.2 on 2024-11-07 14:19

from django.db import migrations


DIRTY = 1
PROCESSING = 2
ERROR = 3


def forwards_func(apps, _):
    DeduplicationSet = apps.get_model("api", "DeduplicationSet")
    DeduplicationSet.objects.filter(state__in=[PROCESSING, ERROR]).update(state=DIRTY)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_remove_deduplicationset_state_value_and_more"),
    ]

    operations = [
        # reverse operation is impossible
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
