# Generated by Django 5.1.4 on 2024-12-31 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_update_deduplication_set_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="deduplicationset",
            name="encodings",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_reference_pk",
                    models.CharField(max_length=100, verbose_name="First reference"),
                ),
                (
                    "second_reference_pk",
                    models.CharField(max_length=100, verbose_name="Second reference"),
                ),
                (
                    "score",
                    models.FloatField(default=0, verbose_name="Similarity Score"),
                ),
                ("error", models.IntegerField(blank=True, null=True)),
                (
                    "deduplication_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.deduplicationset",
                    ),
                ),
            ],
            options={
                "unique_together": {("deduplication_set", "first_reference_pk", "second_reference_pk")},
            },
        ),
        migrations.DeleteModel(
            name="Duplicate",
        ),
    ]
