# Generated by Django 5.1.4 on 2024-12-24 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_update_deduplication_set_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ignoredfilenamepair",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="ignoredfilenamepair",
            name="deduplication_set",
        ),
        migrations.AlterUniqueTogether(
            name="ignoredreferencepkpair",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="ignoredreferencepkpair",
            name="deduplication_set",
        ),
        migrations.RenameField(
            model_name="deduplicationset",
            old_name="config",
            new_name="stored_config",
        ),
        migrations.AddField(
            model_name="deduplicationset",
            name="encodings",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="deduplicationset",
            name="silenced",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_reference_pk",
                    models.CharField(max_length=100, verbose_name="First reference"),
                ),
                (
                    "second_reference_pk",
                    models.CharField(max_length=100, verbose_name="Second reference"),
                ),
                ("score", models.FloatField(default=0)),
                (
                    "deduplication_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.deduplicationset",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("deduplication_set", "first_reference_pk", "second_reference_pk")
                },
            },
        ),
        migrations.DeleteModel(
            name="Duplicate",
        ),
        migrations.DeleteModel(
            name="IgnoredFilenamePair",
        ),
        migrations.DeleteModel(
            name="IgnoredReferencePkPair",
        ),
    ]
