# Generated by Django 5.1.4 on 2025-01-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_deduplicationset_encodings_finding_delete_duplicate"),
    ]

    operations = [
        migrations.AddField(
            model_name="deduplicationset",
            name="encoding_errors",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
