# Generated by Django 5.1.4 on 2025-01-16 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_deduplicationset_encodings_finding_delete_duplicate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finding",
            name="error",
        ),
        migrations.AddField(
            model_name="finding",
            name="first_filename",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="finding",
            name="second_filename",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="finding",
            name="status_code",
            field=models.IntegerField(
                choices=[
                    (200, "deduplication success"),
                    (404, "no file found"),
                    (412, "no face detected"),
                    (429, "multiple faces detected"),
                    (500, "generic error"),
                ],
                default=200,
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="score",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Similarity Score",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="second_reference_pk",
            field=models.CharField(
                default="", max_length=100, verbose_name="Second reference"
            ),
        ),
    ]
