# Generated by Django 5.1.4 on 2025-03-05 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_remove_finding_error_finding_first_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2025, 3, 5, 16, 26, 34, 825703),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finding",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
