# Generated by Django 5.1.5 on 2025-01-28 08:54

import django.db.models.deletion
import hope_dedup_engine.apps.api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_remove_finding_error_finding_first_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deduplicationset",
            name="encoding_errors",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="config",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                validators=[
                    hope_dedup_engine.apps.api.validators.validate_constance_config
                ],
            ),
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.config",
            ),
        ),
    ]
