# Generated by Django 5.1.5 on 2025-07-10 8:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_finding_created_at_finding_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hdetoken",
            name="key",
            field=models.CharField(editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Encoding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("data", models.JSONField()),
                (
                    "deduplication_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.deduplicationset",
                    ),
                ),
            ],
            options={
                "unique_together": {("deduplication_set", "filename")},
            },
        ),
    ]
