# Generated by Django 5.1.5 on 2025-07-10 9:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_hdetoken_key_encoding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deduplicationset",
            name="encodings",
        ),
    ]
