# Generated by Django 5.2.4 on 2025-07-15 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_rename_celery_result_dedupjob_local_status_and_more"),
        ("security", "0002_alter_system_id_alter_user_id_alter_userrole_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="deduplicationset",
            name="system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="security.system",
            ),
        ),
    ]
