# Generated by Django 5.2.4 on 2025-07-15 12:36

from django.db import migrations


def forward(apps, _):
    DeduplicationSet = apps.get_model("api", "DeduplicationSet")
    for deduplication_set in DeduplicationSet.objects.all():
        deduplication_set.system = deduplication_set.external_system.system
        deduplication_set.save()


def backward(apps, _):
    DeduplicationSet = apps.get_model("api", "DeduplicationSet")
    for deduplication_set in DeduplicationSet.objects.all():
        deduplication_set.system = None
        deduplication_set.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_deduplicationset_system"),
        ("security", "0004_create_systems"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
