# Generated by Django 5.2.4 on 2025-07-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_assign_systems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deduplicationset",
            name="external_system",
        ),
    ]
