# Generated by Django 5.2.4 on 2025-07-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_assign_systems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deduplicationset",
            name="external_system",
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="system",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="security.system"),
        ),
    ]
