# Generated by Django 5.2.4 on 2025-07-22 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_remove_deduplicationset_external_system"),
        ("security", "0008_delete_externalsystem"),
    ]

    operations = [
        migrations.AddField(
            model_name="hdetoken",
            name="system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="security.system",
            ),
        ),
    ]
