# Generated by Django 5.2.4 on 2025-07-22 09:29

from django.db import migrations


def forward(apps, _):
    Group = apps.get_model("auth", "Group")
    api_user_group = Group.objects.get(name="API users")

    # we expect one-to-one relation between user role and user here
    for user_role in api_user_group.userrole_set.all():
        user_role.user.auth_tokens.update(system=user_role.system)
        api_user_group.user_set.add(user_role.user)


def backward(apps, _):
    HDEToken = apps.get_model("api", "HDEToken")
    HDEToken.objects.update(system=None)

    Group = apps.get_model("auth", "Group")
    api_user_group = Group.objects.get(name="API users")
    api_user_group.user_set.clear()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_hdetoken_system"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
