# Generated by Django 5.2.4 on 2025-07-22 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_assign_system_to_tokens"),
        ("security", "0008_delete_externalsystem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hdetoken",
            name="system",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="security.system"),
        ),
    ]
