# Generated by Django 5.2.4 on 2025-07-22 10:54

from django.db import migrations


def forward(apps, _):
    Group = apps.get_model("auth", "Group")
    api_user_group = Group.objects.get(name="API users")
    api_user_group.userrole_set.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_alter_hdetoken_system"),
    ]

    operations = [
        # cannot undo this step
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
