# Generated by Django 5.2.4 on 2025-07-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_clear_user_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deduplicationset",
            name="state",
            field=models.IntegerField(
                choices=[
                    (0, "Ready"),
                    (1, "Modified"),
                    (2, "Processing"),
                    (3, "Failed"),
                ],
                db_column="state",
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="deduplicationset",
            name="error",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
