# Generated by Django 5.2.5 on 2025-09-30 08:49
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("api", "0028_deduplicationset_state_and_error"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="finding",
            index=models.Index(
                fields=["deduplication_set", "-updated_at", "-id"],
                name="finding_order_idx",
            ),
        ),
    ]
