# Generated by Django 5.2.5 on 2025-09-13 10:42

from pgvector.django import VectorExtension
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_deduplicationset_state_and_error"),
    ]

    operations = [
        VectorExtension(),
        migrations.RemoveField(
            model_name="encoding",
            name="data",
        ),
        migrations.AddField(
            model_name="encoding",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
        migrations.AddField(
            model_name="encoding",
            name="status_code",
            field=models.IntegerField(
                choices=[
                    (200, "deduplication success"),
                    (404, "no file found"),
                    (412, "no face detected"),
                    (429, "multiple faces detected"),
                    (500, "generic error"),
                ],
                default=200,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="encoding",
            index=pgvector.django.indexes.HnswIndex(
                fields=["embedding"],
                name="encoding_embedding_idx",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
