# Generated by Django 5.2.5 on 2025-09-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_deduplicationset_state_and_error"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["deduplication_set", "-updated_at", "-id"],
                name="finding_order_idx",
            ),
        ),
    ]
