# Generated by Django 5.2.6 on 2025-09-14 11:09

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_remove_encoding_data_encoding_embedding_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="encoding",
            name="encoding_embedding_idx",
        ),
        migrations.AddIndex(
            model_name="encoding",
            index=pgvector.django.indexes.IvfflatIndex(
                fields=["embedding"],
                lists=100,
                name="encoding_embedding_idx",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
