# Generated by Django 5.2.5 on 2025-10-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_finding_finding_order_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="encoding",
            index=models.Index(fields=["filename"], name="api_encodin_filenam_50e86a_idx"),
        ),
    ]
