# Generated by Django 5.2.5 on 2025-10-03 11:55

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_encoding_api_encodin_filenam_50e86a_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="encoding",
            name="api_encodin_filenam_50e86a_idx",
        ),
        migrations.AlterUniqueTogether(
            name="encoding",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="finding",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="ignoredfilenamepair",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="ignoredreferencepkpair",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="encoding",
            name="embedding",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="encoding",
            name="status_code",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (200, "deduplication success"),
                    (404, "no file found"),
                    (412, "no face detected"),
                    (429, "multiple faces detected"),
                    (500, "generic error"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="encoding",
            name="filename",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="ignoredfilenamepair",
            name="first",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="ignoredfilenamepair",
            name="second",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["deduplication_set", "filename"],
                name="api_image_dedupli_56b2aa_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="encoding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("embedding__isnull", False), ("status_code__isnull", True)),
                    models.Q(("embedding__isnull", True), ("status_code__isnull", False)),
                    _connector="OR",
                ),
                name="encoding_embedding_or_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                fields=(
                    "deduplication_set",
                    "first_reference_pk",
                    "second_reference_pk",
                ),
                name="unique_finding",
            ),
        ),
        migrations.AddConstraint(
            model_name="ignoredfilenamepair",
            constraint=models.UniqueConstraint(
                fields=("deduplication_set", "first", "second"),
                name="unique_ignored_filename_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="ignoredreferencepkpair",
            constraint=models.UniqueConstraint(
                fields=("deduplication_set", "first", "second"),
                name="unique_ignored_ref_pair",
            ),
        ),
        migrations.AlterField(
            model_name="encoding",
            name="data",
            field=models.JSONField(null=True, blank=True, default=list),
        ),
        migrations.RemoveField(
            model_name="encoding",
            name="data",
        ),
        migrations.RemoveField(
            model_name="encoding",
            name="deduplication_set",
        ),
    ]
