# Generated by Django 5.2.5 on 2025-10-02 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_encoding_api_encodin_filenam_50e86a_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dedupjob",
            name="serialized_lock",
        ),
        migrations.AlterField(
            model_name="dedupjob",
            name="deduplication_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dedup_jobs",
                to="api.deduplicationset",
            ),
        ),
    ]
