# Generated by Django 5.2.5 on 2025-09-30 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_encoding_api_encodin_filenam_50e86a_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="dedupjob",
            name="files_data",
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="dedupjob",
            name="deduplication_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dedup_jobs",
                to="api.deduplicationset",
            ),
        ),
    ]
