# Generated by Django 5.2.5 on 2025-10-02 12:57

from itertools import batched
from django.db import migrations, models
from django.db.models import Q
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


BATCH_SIZE = 1000
STATUS_CODE_MAP = {
    "DEDUPLICATE_SUCCESS": 200,
    "NO_FILE_FOUND": 404,
    "NO_FACE_DETECTED": 412,
    "MULTIPLE_FACES_DETECTED": 429,
    "GENERIC_ERROR": 500,
}


def migrate_encoding_data_batched(apps: Apps, _: BaseDatabaseSchemaEditor) -> None:
    Encoding = apps.get_model("api", "Encoding")

    def process_encoding(enc):
        if enc.data is not None:
            if isinstance(enc.data, list):
                enc.embedding = enc.data
                enc.status_code = None
            else:
                enc.embedding = None
                enc.status_code = STATUS_CODE_MAP.get(enc.data, 500)
        else:
            enc.embedding = None
            enc.status_code = 500
        return enc

    encodings = (process_encoding(enc) for enc in Encoding.objects.iterator(chunk_size=BATCH_SIZE))

    for batch in batched(encodings, BATCH_SIZE):  # noqa: B911
        Encoding.objects.bulk_update(list(batch), ["embedding", "status_code"], batch_size=BATCH_SIZE)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_alter_encoding_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrate_encoding_data_batched,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="encoding",
            constraint=models.CheckConstraint(
                condition=Q(
                    Q(embedding__isnull=False, status_code__isnull=True)
                    | Q(embedding__isnull=True, status_code__isnull=False)
                ),
                name="encoding_embedding_or_status",
            ),
        ),
        migrations.RemoveField(
            model_name="encoding",
            name="data",
        ),
    ]
