# Generated by Django 5.2.5 on 2025-10-03 14:06

from django.db import migrations


def clean_encoding_table(apps, schema_editor):
    Encoding = apps.get_model("api", "Encoding")
    Encoding.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_encoding_api_encodin_filenam_50e86a_idx"),
    ]

    run_before = [
        ("api", "0031_remove_encoding_api_encodin_filenam_50e86a_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(
            clean_encoding_table,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
