# Generated by Django 5.2.5 on 2025-10-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_remove_dedupjob_serialized_lock_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["deduplication_set", "first_reference_pk"],
                name="finding_first_ref_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["deduplication_set", "second_reference_pk"],
                name="finding_second_ref_idx",
            ),
        ),
    ]
