# Generated by Django 5.2.5 on 2025-10-06 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_finding_finding_first_ref_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeduplicationChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("ready", models.BooleanField(default=False)),
                (
                    "deduplication_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.deduplicationset",
                    ),
                ),
            ],
        ),
    ]
