# Generated by Django 5.2.5 on 2025-10-30 16:42
from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.models import Count
from django.db.models.functions import Concat


def remove_duplicate_images(apps: Apps, _: BaseDatabaseSchemaEditor) -> None:
    Image = apps.get_model("api", "Image")

    # count images with the same deduplication_set and reference_pk
    duplicates = (
        Image.objects.values("deduplication_set", "reference_pk")
        .annotate(records=Count(Concat("deduplication_set", "reference_pk")))
        .filter(records__gt=1)
    )

    for duplicate in duplicates:
        # sort images newest to oldest
        images = Image.objects.filter(
            deduplication_set=duplicate["deduplication_set"], reference_pk=duplicate["reference_pk"]
        ).order_by("-created_at")

        # we keep the newest only
        for image in images[1:]:
            image.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_finding_finding_first_ref_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_images, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="image",
            unique_together={("deduplication_set", "reference_pk")},
        ),
    ]
