# Generated by Django 5.2.5 on 2025-10-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_alter_image_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="deduplicationset",
            name="total_pairs",
            field=models.IntegerField(default=0),
        ),
    ]
