# Generated by Django 5.2.9 on 2025-12-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_alter_image_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encoding",
            name="status_code",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (200, "deduplication success"),
                    (404, "no file found"),
                    (412, "no face detected"),
                    (416, "face was detected but did not meet confidence threshold"),
                    (429, "multiple faces detected"),
                    (500, "generic error"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="status_code",
            field=models.IntegerField(
                choices=[
                    (200, "deduplication success"),
                    (404, "no file found"),
                    (412, "no face detected"),
                    (416, "face was detected but did not meet confidence threshold"),
                    (429, "multiple faces detected"),
                    (500, "generic error"),
                ],
                default=200,
            ),
        ),
    ]
