# Generated by Django 5.2.9 on 2025-12-15 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_alter_image_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="finding",
            options={"permissions": [("view_finding_details", "Can view finding details")]},
        ),
    ]
