# Generated by Django 5.2.9 on 2025-12-02 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0036_deduplicationsetgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="deduplicationset",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.deduplicationsetgroup",
            ),
        ),
    ]
