# Generated by Django 5.2.9 on 2025-12-02 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0036_alter_encoding_status_code_alter_finding_status_code"),
        ("security", "0008_delete_externalsystem"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeduplicationSetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_pk", models.CharField(max_length=100, unique=True)),
                ("settings", models.JSONField(blank=True, default=dict, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="security.system",
                    ),
                ),
            ],
        ),
    ]
