# Generated by Django 5.2.9 on 2025-12-02 19:00

from django.db import migrations
from django.db.migrations.state import StateApps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def forward(apps: StateApps, _: BaseDatabaseSchemaEditor):
    DeduplicationSet = apps.get_model("api", "DeduplicationSet")
    DeduplicationSetGroup = apps.get_model("api", "DeduplicationSetGroup")
    for deduplication_set in DeduplicationSet.objects.filter(deleted=False):
        deduplication_set_group = DeduplicationSetGroup.objects.create(
            reference_pk=deduplication_set.reference_pk, system=deduplication_set.system
        )
        deduplication_set.group = deduplication_set_group
        deduplication_set.save()
    DeduplicationSet.objects.filter(deleted=True).delete()


def backward(apps: StateApps, _: BaseDatabaseSchemaEditor):
    DeduplicationSetGroup = apps.get_model("api", "DeduplicationSetGroup")
    for deduplication_set_group in DeduplicationSetGroup.objects.all():
        for deduplication_set in deduplication_set_group.deduplication_set_set.all():
            deduplication_set.reference_pk = deduplication_set_group.reference_pk
            deduplication_set.system = deduplication_set_group.system
            deduplication_set.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_deduplicationset_group"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
