# Generated by Django 5.2.9 on 2025-12-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_create_deduplication_set_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deduplicationset",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.deduplicationsetgroup",
            ),
        ),
    ]
