# Generated by Django 5.2.9 on 2025-12-02 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_alter_deduplicationset_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deduplicationset",
            name="config",
        ),
        migrations.RemoveField(
            model_name="deduplicationset",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="deduplicationset",
            name="reference_pk",
        ),
        migrations.RemoveField(
            model_name="deduplicationset",
            name="system",
        ),
        migrations.DeleteModel(
            name="Config",
        ),
    ]
