# Generated by Django 5.2.9 on 2025-12-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_remove_deduplicationset_config_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deduplicationset",
            name="state",
            field=models.IntegerField(
                choices=[
                    (0, "Ready"),
                    (1, "Modified"),
                    (2, "Processing"),
                    (3, "Failed"),
                    (4, "Approved"),
                    (5, "Rejected"),
                ],
                db_column="state",
                default=0,
            ),
        ),
    ]
