# Generated by Django 5.2.9 on 2025-12-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0041_alter_deduplicationset_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="state",
            field=models.IntegerField(choices=[(0, "Active"), (1, "Approved"), (2, "Rejected")], default=0),
        ),
    ]
