# Generated by Django 5.2.9 on 2025-12-05 11:44

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0043_image_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Encoding",
        ),
        migrations.AddField(
            model_name="image",
            name="embedding",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="embedding_status_code",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (200, "deduplication success"),
                    (404, "no file found"),
                    (412, "no face detected"),
                    (416, "face was detected but did not meet confidence threshold"),
                    (429, "multiple faces detected"),
                    (500, "generic error"),
                ],
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("embedding__isnull", True),
                        ("embedding_status_code__isnull", True),
                    ),
                    models.Q(
                        ("embedding__isnull", False),
                        ("embedding_status_code__isnull", True),
                    ),
                    models.Q(
                        ("embedding__isnull", True),
                        ("embedding_status_code__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="encoding_embedding_or_status",
            ),
        ),
    ]
