# Generated by Django 5.2.9 on 2025-12-05 12:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0044_delete_encoding_image_embedding_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="Encoding",
        ),
        migrations.RenameIndex(
            model_name="encoding",
            new_name="api_encodin_dedupli_909c41_idx",
            old_name="api_image_dedupli_56b2aa_idx",
        ),
    ]
