# Generated by Django 5.2.9 on 2025-12-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0045_rename_image_encoding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deduplicationset",
            name="notify",
            field=models.BooleanField(default=True),
        ),
    ]
