# Generated by Django 5.2.9 on 2025-12-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0046_deduplicationset_notify"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deduplicationset",
            name="state",
            field=models.IntegerField(
                choices=[
                    (0, "Ready"),
                    (1, "Modified"),
                    (2, "Processing"),
                    (3, "Failed"),
                    (4, "Inactive"),
                ],
                db_column="state",
                default=0,
            ),
        ),
    ]
