# Generated by Django 5.2.9 on 2025-12-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0047_alter_deduplicationset_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="deduplicationset",
            name="settings",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
