# Generated by Django 5.2.9 on 2025-12-10 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0048_deduplicationset_settings"),
        ("security", "0008_delete_externalsystem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="finding",
            options={"permissions": [("view_finding_details", "Can view finding details")]},
        ),
        migrations.AlterField(
            model_name="deduplicationsetgroup",
            name="deleted",
            field=models.BooleanField(default=False, help_text="Whether this group was deleted."),
        ),
        migrations.AlterField(
            model_name="deduplicationsetgroup",
            name="reference_pk",
            field=models.CharField(
                help_text="External id used to group deduplication sets.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="deduplicationsetgroup",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Settings common for all deduplication sets in this group.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deduplicationsetgroup",
            name="system",
            field=models.ForeignKey(
                help_text="System API user belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                to="security.system",
            ),
        ),
    ]
