# Generated by Django 5.2.9 on 2025-12-11 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0049_alter_finding_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="first_encoding",
            field=models.ForeignKey(
                to="api.encoding",
                on_delete=django.db.models.deletion.CASCADE,
                null=True,
                blank=True,
                related_name="first_findings",
                help_text="First encoding in this potential duplicate pair.",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="second_encoding",
            field=models.ForeignKey(
                to="api.encoding",
                on_delete=django.db.models.deletion.CASCADE,
                null=True,
                blank=True,
                related_name="second_findings",
                help_text="Second encoding in this potential duplicate pair.",
            ),
        ),
    ]
