# Generated by Django 5.2.9 on 2025-12-11 06:24

from django.db import migrations, models
import django.db.models.deletion


def clear_findings(apps, schema_editor):
    """Drop existing Finding rows before enforcing NOT NULL on new FKs."""
    Finding = apps.get_model("api", "Finding")
    Finding.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0050_finding_add_encoding_fk"),
    ]

    operations = [
        migrations.RunPython(clear_findings, migrations.RunPython.noop),
        migrations.RemoveConstraint(model_name="finding", name="unique_finding"),
        migrations.RemoveIndex(model_name="finding", name="finding_first_ref_idx"),
        migrations.RemoveIndex(model_name="finding", name="finding_second_ref_idx"),
        migrations.RemoveField(model_name="finding", name="first_reference_pk"),
        migrations.RemoveField(model_name="finding", name="first_filename"),
        migrations.RemoveField(model_name="finding", name="second_reference_pk"),
        migrations.RemoveField(model_name="finding", name="second_filename"),
        migrations.AlterField(
            model_name="finding",
            name="first_encoding",
            field=models.ForeignKey(
                to="api.encoding",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_findings",
                help_text="First encoding in this potential duplicate pair.",
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["deduplication_set", "first_encoding"],
                name="finding_first_encoding_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["deduplication_set", "second_encoding"],
                name="finding_second_encoding_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                fields=["deduplication_set", "first_encoding", "second_encoding"],
                name="unique_finding",
            ),
        ),
    ]
