# Generated by Django 5.2.9 on 2025-12-15 15:56

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0051_finding_switch_to_encoding_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="deduplicationset",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when this deduplication set was created.",
            ),
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this deduplication set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="description",
            field=models.TextField(blank=True, help_text="Deduplication set description.", null=True),
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="error",
            field=models.CharField(blank=True, help_text="Error message.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="group",
            field=models.ForeignKey(
                help_text="Deduplication set group.",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.deduplicationsetgroup",
            ),
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Deduplication set id.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Deduplication set name.",
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="notification_url",
            field=models.CharField(blank=True, help_text="Notification url.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="notify",
            field=models.BooleanField(
                default=True,
                help_text="Whether to send notifications about deduplication set state changes.",
            ),
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Deduplication set settings.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="state",
            field=models.IntegerField(
                choices=[
                    (0, "Ready"),
                    (1, "Modified"),
                    (2, "Processing"),
                    (3, "Failed"),
                    (4, "Inactive"),
                ],
                db_column="state",
                default=0,
                help_text="Deduplication set state.",
            ),
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when this deduplication set was last updated.",
            ),
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this deduplication set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="encoding",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when this encoding was created.",
            ),
        ),
        migrations.AlterField(
            model_name="encoding",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this encoding.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="encoding",
            name="deduplication_set",
            field=models.ForeignKey(
                help_text="Deduplication set.",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.deduplicationset",
            ),
        ),
        migrations.AlterField(
            model_name="encoding",
            name="embedding",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                blank=True,
                help_text="Embedding vector.",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="encoding",
            name="embedding_status_code",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (200, "deduplication success"),
                    (404, "no file found"),
                    (412, "no face detected"),
                    (416, "face was detected but did not meet confidence threshold"),
                    (429, "multiple faces detected"),
                    (500, "generic error"),
                ],
                help_text="Embedding status code.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="encoding",
            name="filename",
            field=models.CharField(help_text="Filename used in encoding.", max_length=255),
        ),
        migrations.AlterField(
            model_name="encoding",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Encoding id.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="encoding",
            name="reference_pk",
            field=models.CharField(help_text="External id of the encoding.", max_length=100),
        ),
        migrations.AlterField(
            model_name="encoding",
            name="state",
            field=models.IntegerField(
                choices=[(0, "Active"), (1, "Approved"), (2, "Rejected")],
                default=0,
                help_text="Encoding state.",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when this finding was created.",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="deduplication_set",
            field=models.ForeignKey(
                help_text="Deduplication set.",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.deduplicationset",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="score",
            field=models.FloatField(
                default=0,
                help_text="Similarity score between the two encodings.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Similarity Score",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="status_code",
            field=models.IntegerField(
                choices=[
                    (200, "deduplication success"),
                    (404, "no file found"),
                    (412, "no face detected"),
                    (416, "face was detected but did not meet confidence threshold"),
                    (429, "multiple faces detected"),
                    (500, "generic error"),
                ],
                default=200,
                help_text="Finding status code.",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Date and time when this finding was updated."),
        ),
        migrations.AlterField(
            model_name="ignoredfilenamepair",
            name="deduplication_set",
            field=models.ForeignKey(
                help_text="Deduplication set.",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.deduplicationset",
            ),
        ),
        migrations.AlterField(
            model_name="ignoredfilenamepair",
            name="first",
            field=models.CharField(help_text="First filename.", max_length=255),
        ),
        migrations.AlterField(
            model_name="ignoredfilenamepair",
            name="second",
            field=models.CharField(help_text="Second filename.", max_length=255),
        ),
        migrations.AlterField(
            model_name="ignoredreferencepkpair",
            name="deduplication_set",
            field=models.ForeignKey(
                help_text="Deduplication set.",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.deduplicationset",
            ),
        ),
        migrations.AlterField(
            model_name="ignoredreferencepkpair",
            name="first",
            field=models.CharField(help_text="First reference pk.", max_length=100),
        ),
        migrations.AlterField(
            model_name="ignoredreferencepkpair",
            name="second",
            field=models.CharField(help_text="Second reference pk.", max_length=100),
        ),
    ]
