# Generated by Django 5.2.9 on 2025-12-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0052_deduplication_set_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="dedupjob",
            name="encode_only",
            field=models.BooleanField(default=False),
        ),
    ]
