# Generated by Django 5.2.9 on 2025-12-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0053_dedupjob_encode_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encoding",
            name="embedding_status_code",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (200, "deduplication success"),
                    (404, "no file found"),
                    (412, "no face detected"),
                    (416, "face was detected but did not meet confidence threshold"),
                    (417, "face does not cover sufficient part of the image"),
                    (429, "multiple faces detected"),
                    (500, "generic error"),
                ],
                help_text="Embedding status code.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="status_code",
            field=models.IntegerField(
                choices=[
                    (200, "deduplication success"),
                    (404, "no file found"),
                    (412, "no face detected"),
                    (416, "face was detected but did not meet confidence threshold"),
                    (417, "face does not cover sufficient part of the image"),
                    (429, "multiple faces detected"),
                    (500, "generic error"),
                ],
                default=200,
                help_text="Finding status code.",
            ),
        ),
    ]
