# Generated by Django 5.2.9 on 2025-12-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0053_dedupjob_encode_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="deduplicationsetgroup",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Deduplication set group name.",
                max_length=128,
                null=True,
            ),
        ),
    ]
