# Generated by Django 5.2.9 on 2025-12-18 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0055_deduplicationsetgroup_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="encoding",
            name="face_coverage",
            field=models.FloatField(
                blank=True,
                help_text="Face bbox area divided by image area (0..1).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
