# Generated by Django 5.2.9 on 2025-12-30 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0056_encoding_face_coverage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deduplicationset",
            options={
                "permissions": [
                    ("clear_embeddings", "Can clear embeddings"),
                    ("export_findings", "Can export findings"),
                    ("process_encodings", "Can process encodings"),
                    ("process_deduplicate", "Can process deduplication"),
                    ("remove_findings", "Can remove findings"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="encoding",
            options={"permissions": [("detect_faces", "Can detect faces")]},
        ),
    ]
