# Generated by Django 5.2.10 on 2026-01-21 12:23
from typing import Final

from django.apps.registry import Apps
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


INACTIVE_STATE: Final[int] = 4
REJECTED_STATE: Final[int] = 2


def reject_unapproved_deduplication_sets(apps: Apps, _: BaseDatabaseSchemaEditor) -> None:
    DeduplicationSet = apps.get_model("api", "DeduplicationSet")

    groups_to_cleanup = (
        DeduplicationSet.objects.values("group").annotate(records=models.Count("group")).filter(records__gt=1)
    )

    for group in groups_to_cleanup:
        deduplication_sets = DeduplicationSet.objects.filter(group=group["group"]).order_by("-created_at")
        for deduplication_set in deduplication_sets[1:]:
            deduplication_set.encoding_set.update(state=REJECTED_STATE)
            deduplication_set.state = INACTIVE_STATE
            deduplication_set.save(update_fields=["state"])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0058_callbackfindingsjob_dedupechunkjob_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(reject_unapproved_deduplication_sets, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="deduplicationset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", INACTIVE_STATE), _negated=True),
                fields=("group",),
                name="unique_active_deduplication_set_per_group",
            ),
        ),
    ]
