# Generated by Django 5.2.10 on 2026-01-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0059_deduplicationset_unique_active_deduplication_set_per_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encoding",
            name="filename",
            field=models.TextField(help_text="Filename or data URL used in encoding."),
        ),
    ]
