# Generated by Django 5.2.10 on 2026-01-26 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0060_alter_encoding_filename"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="encoding",
            name="api_encodin_dedupli_909c41_idx",
        ),
    ]
