# Generated by Django 5.2.10 on 2026-03-04 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0063_alter_encoding_embedding_status_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="encoding",
            name="michelson_contrast",
            field=models.FloatField(
                blank=True,
                help_text="Michelson contrast calculated on the image.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
