# Generated by Django 5.2.12 on 2026-03-23 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0064_encoding_image_quality_scores"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deduplicationset",
            name="unique_active_deduplication_set_per_group",
        ),
        migrations.RemoveField(
            model_name="encoding",
            name="state",
        ),
        migrations.AlterField(
            model_name="deduplicationset",
            name="state",
            field=models.IntegerField(
                choices=[
                    (0, "Ready"),
                    (1, "Modified"),
                    (2, "Processing"),
                    (3, "Failed"),
                    (4, "Inactive"),
                    (5, "Rejected"),
                ],
                db_column="state",
                default=0,
                help_text="Deduplication set state.",
            ),
        ),
        migrations.AddConstraint(
            model_name="deduplicationset",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("state", 4), _negated=True),
                    models.Q(("state", 5), _negated=True),
                    models.Q(("state", 3), _negated=True),
                ),
                fields=("group",),
                name="unique_active_deduplication_set_per_group",
            ),
        ),
    ]
