# Generated by Django 5.2.14 on 2026-07-20 10:32

import hope_dedup_engine.apps.api.models.deduplication
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0073_encoding_filename_filefield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encoding",
            name="embedding_status_code",
            field=models.IntegerField(
                blank=True,
                choices=hope_dedup_engine.apps.api.models.deduplication.Encoding.StatusCode.field_choices,
                help_text="Embedding status code.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="encoding",
            name="filename",
            field=models.CharField(
                help_text="Filename (path/key) in the shared HOPE blob storage.",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="status_code",
            field=models.IntegerField(
                choices=hope_dedup_engine.apps.api.models.deduplication.Encoding.StatusCode.field_choices,
                default=200,
                help_text="Finding status code.",
            ),
        ),
    ]
