# Generated by Django 5.2.17 on 2026-08-27 07:00

import hope_dedup_engine.apps.api.models.deduplication
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0073_encoding_filename_filefield"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deduplicationsetgroup",
            options={"permissions": [("release_processing_lock", "Can release processing lock")]},
        ),
        migrations.AlterField(
            model_name="encoding",
            name="embedding_status_code",
            field=models.IntegerField(
                blank=True,
                choices=hope_dedup_engine.apps.api.models.deduplication.get_encoding_status_choices,
                help_text="Embedding status code.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="status_code",
            field=models.IntegerField(
                choices=hope_dedup_engine.apps.api.models.deduplication.get_encoding_status_choices,
                default=200,
                help_text="Finding status code.",
            ),
        ),
    ]
