# Generated by Django 5.2.14 on 2026-07-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0075_remove_deduplicationsetgroup_system_delete_hdetoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encoding",
            name="filename",
            field=models.CharField(
                help_text="Filename (path/key) in the shared HOPE blob storage.",
                max_length=1024,
            ),
        ),
    ]
