# Generated by Django 5.2.4 on 2025-07-15 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0002_alter_system_id_alter_user_id_alter_userrole_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalsystem",
            name="system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="security.system",
            ),
        ),
    ]
