# Generated by Django 5.2.4 on 2025-07-15 11:32

from django.db import migrations


def forward(apps, _):
    ExternalSystem = apps.get_model("security", "ExternalSystem")
    System = apps.get_model("security", "System")

    for external_system in ExternalSystem.objects.all():
        external_system.system = System.objects.create(name=external_system.name)
        external_system.save()


def backward(apps, _):
    ExternalSystem = apps.get_model("security", "ExternalSystem")

    for external_system in ExternalSystem.objects.all():
        if external_system.system:
            external_system.system.delete()
            external_system.system = None
            external_system.save()


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0003_add_system_ref_to_externalsystem"),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
