# Generated by Django 5.2.4 on 2025-07-15 11:46

from django.db import migrations


CAN_USE_API_CODENAME = "can_use_api"
API_USERS_GROUP_NAME = "API users"


def forward(apps, _):
    DeduplicationSet = apps.get_model("api", "DeduplicationSet")
    ContentType = apps.get_model("contenttypes", "ContentType")
    deduplication_set_content_type = ContentType.objects.get_for_model(DeduplicationSet)

    Permission = apps.get_model("auth", "Permission")
    can_use_api_permission = Permission.objects.create(
        codename=CAN_USE_API_CODENAME,
        name="Can use API",
        content_type=deduplication_set_content_type,
    )

    Group = apps.get_model("auth", "Group")
    api_user_group, _ = Group.objects.get_or_create(name=API_USERS_GROUP_NAME)
    api_user_group.permissions.add(can_use_api_permission)


def backward(apps, _):
    Group = apps.get_model("auth", "Group")
    Group.objects.get(name=API_USERS_GROUP_NAME).delete()

    DeduplicationSet = apps.get_model("api", "DeduplicationSet")
    ContentType = apps.get_model("contenttypes", "ContentType")
    deduplication_set_content_type = ContentType.objects.get_for_model(DeduplicationSet)

    Permission = apps.get_model("auth", "Permission")
    Permission.objects.get(
        codename=CAN_USE_API_CODENAME,
        content_type=deduplication_set_content_type,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0004_create_systems"),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
