# Generated by Django 5.2.4 on 2025-07-15 12:22
from django.db import migrations


API_USERS_GROUP_NAME = "API users"

def forward(apps, _):
    User = apps.get_model('security', 'User')
    UserRole = apps.get_model('security', 'UserRole')
    Group = apps.get_model("auth", "Group")
    api_user_group = Group.objects.get(name=API_USERS_GROUP_NAME)
    for user in User.objects.filter(external_system__isnull=False):
        UserRole.objects.create(
            user=user,
            group=api_user_group,
            system=user.external_system.system,
        )


def backward(apps, _):
    Group = apps.get_model("auth", "Group")
    api_user_group = Group.objects.get(name=API_USERS_GROUP_NAME)
    UserRole = apps.get_model('security', 'UserRole')
    UserRole.objects.filter(group=api_user_group).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0005_create_group_and_permission"),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
