# Generated by Django 5.2.4 on 2025-07-15 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0006_assign_userroles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="external_system",
        ),
    ]
