# Generated by Django 5.2.4 on 2025-07-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0007_remove_user_external_system"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExternalSystem",
        ),
    ]
