#!/usr/bin/env bash

start_time=$(date +%s)

source "$(dirname "0")/.common"

if [[ $# -ne 1 ]] ; then
  show_required_args "deduplication set reference pk"
  exit 1
fi

./create_deduplication_set "$1"

files=()
for path in ../demo_images/*.{jpg,png}; do
  file=$(basename $path)
  if [[ -f "$path" ]] && [ "$file" != "too_small.jpg" ] && [ "$file" != "without_face.jpg" ]; then
    files+=("$file")
  fi
done

last_idx=$(( ${#files[@]} - 1 ))
for i in "${!files[@]}"; do
  if [[ $i -eq $last_idx ]]; then
    ./create_image "${files[$i]}" "${files[$i]}" --last
  else
    ./create_image "${files[$i]}" "${files[$i]}"
  fi
done


./process_deduplication_set

./show_duplicates

duration=$(( $(date +%s) - start_time ))
echo "Duration: $duration seconds."
