#!/usr/bin/env bash

start_time=$(date +%s)

source "$(dirname "0")/.common"

if [[ $# -ne 1 ]] ; then
  show_required_args "deduplication set reference pk"
  exit 1
fi

./create_deduplication_set "$1" | jq -r ".id" | xargs ./use_deduplication_set

for file in ../demo_images/*.{jpg,jpeg,png}; do
  if [[ -f "$file" ]]; then
    ./create_image $(basename "$file")
  fi
done

./process_deduplication_set

./show_duplicates

duration=$(( $(date +%s) - start_time ))
echo "Duration: $duration seconds."
