#!/usr/bin/env bash

start_time=$(date +%s)

source "$(dirname "0")/.common"

if [[ $# -ne 1 ]] ; then
  show_required_args "deduplication set reference pk"
  exit 1
fi

./create_deduplication_set "$1"

for path in ../demo_images/*.{jpg,png}; do
  file=$(basename $path)
  if [[ -f "$path" ]] && [ "$file" != "too_small.jpg" ] && [ "$file" != "without_face.jpg" ]; then
    ./create_image "$file" "data:$(mimetype -b "$path");base64,$(base64 "$path")"
  fi
done


./process_deduplication_set

./show_duplicates

duration=$(( $(date +%s) - start_time ))
echo "Duration: $duration seconds."
