#!/usr/bin/env bash

start_time=$(date +%s)

source "$(dirname "0")/.common"

if [[ $# -ne 1 ]] ; then
  show_required_args "deduplication set reference pk"
  exit 1
fi

./create_deduplication_set "$1"
source "$(dirname "0")/.vars"

payload="["
first=true
for path in ../demo_images/*.{jpg,png}; do
  file=$(basename "$path")
  if [[ -f "$path" ]] && [ "$file" != "too_small.jpg" ] && [ "$file" != "without_face.jpg" ]; then
    encoded="data:$(mimetype -b "$path");base64,$(base64 -w0 "$path")"
    if [ "$first" = true ]; then
      first=false
    else
      payload+=","
    fi
    payload+="{\"reference_pk\": \"$file\", \"filename\": \"$encoded\"}"
  fi
done
payload+="]"

printf '%s' "$payload" \
  | call_api POST "deduplication_sets/$DEDUPLICATION_SET_ID/images" Content-Type:application/json last==true


./process_deduplication_set

./show_duplicates

duration=$(( $(date +%s) - start_time ))
echo "Duration: $duration seconds."
