#!/usr/bin/env bash

source "$(dirname "0")/.common"

echo Create image >&2

# We use image name provided as both reference pk and filename

if [[ $# -ne 1 ]] ; then
  show_required_args filename
  exit 1
fi

call_api POST "deduplication_sets/$DEDUPLICATION_SET_ID/images" reference_pk="$1" filename="$1"
