#!/usr/bin/env bash

source "$(dirname "0")/.common"

echo Create deduplication set >&2

if [[ $# -ne 1 ]] ; then
  show_required_args "reference pk"
  exit 1
fi

response=$(call_api POST deduplication_sets reference_pk="$1")
echo "$response"

set_variable DEDUPLICATION_SET_REFERENCE_PK "$1"
set_variable DEDUPLICATION_SET_ID "$(echo "$response" | jq -r '.id')"
