#!/usr/bin/env bash

source "$(dirname "0")/.common"

echo Create image >&2

if [[ $# -lt 2 ]] ; then
  show_required_args reference_pk filename
  exit 1
fi

args=()
if [[ "$3" == "--last" ]]; then
  args+=(last==true)
fi

printf '[{"reference_pk": "%s", "filename": "%s"}]' "$1" "$2" \
  | call_api POST "deduplication_sets/$DEDUPLICATION_SET_ID/images" Content-Type:application/json "${args[@]}"
