#!/usr/bin/env bash

source "$(dirname "0")/.common"

echo Process deduplication set >&2

call_api POST "deduplication_sets/$DEDUPLICATION_SET_ID/process"

./show_deduplication_set

until [ "$(./show_deduplication_set | jq -r ".state")" != "Processing" ]
do
  sleep 0.5
done

./show_deduplication_set
