from hope_dedup_engine.config import env

ELASTICSEARCH_HOST = env("ELASTICSEARCH_HOST")
ELASTICSEARCH_PREFIX = env("ELASTICSEARCH_PREFIX")
ELASTICSEARCH_SYNONYMS_FILE = env("ELASTICSEARCH_SYNONYMS_FILE")
