from hope_dedup_engine.config import env

AZURE_ACCOUNT_NAME = env("AZURE_ACCOUNT_NAME")
AZURE_ACCOUNT_KEY = env("AZURE_ACCOUNT_KEY")
AZURE_CUSTOM_DOMAIN = env("AZURE_CUSTOM_DOMAIN")
AZURE_CONNECTION_STRING = env("AZURE_CONNECTION_STRING")

AZURE_CONTAINER_HDE = "hde"
AZURE_CONTAINER_HOPE = "hope"

CV2DNN_PATH = env("CV2DNN_PATH")
PROTOTXT_FILE = f"{CV2DNN_PATH}/deploy.prototxt"
CAFFEMODEL_FILE = f"{CV2DNN_PATH}/res10_300x300_ssd_iter_140000.caffemodel"
