name: 'Get Last commit'
description: ''
runs:
  using: "composite"
  steps:
    - name: Setup Environment (PR)  
      if: ${{ github.event_name == 'pull_request' }}  
      shell: bash  
      run: |  
        echo "last_commit_sha=${{ github.event.pull_request.head.sha }}" >> ${GITHUB_ENV}
    - name: Setup Environment (Push)  
      if: ${{ github.event_name == 'push' }}  
      shell: bash
      run: |  
        echo "last_commit_sha=${GITHUB_SHA}" >> ${GITHUB_ENV}