DEDUPLICATION_SET = "deduplication_set"
DEDUPLICATION_SET_LIST = f"{DEDUPLICATION_SET}s"

PK = "pk"
DEDUPLICATION_SET_PARAM = f"{DEDUPLICATION_SET}_{PK}"
DEDUPLICATION_SET_FILTER = f"{DEDUPLICATION_SET}__{PK}"

IMAGE = "image"
IMAGE_LIST = f"{IMAGE}s"

BULK = "bulk"
BULK_IMAGE = f"{IMAGE}_{BULK}"
BULK_IMAGE_LIST = f"{IMAGE_LIST}_{BULK}"
