DEDUPLICATION_SET = "deduplication_set"
DEDUPLICATION_SET_LIST = f"{DEDUPLICATION_SET}s"

PK = "pk"
GROUP = "group"
REFERENCE = "reference"
GROUP_REFERENCE_PK = f"{GROUP}__{REFERENCE}_{PK}"
DEDUPLICATION_SET_GROUP_PARAM = f"{DEDUPLICATION_SET}_{GROUP_REFERENCE_PK}"
DEDUPLICATION_SET_GROUP_FILTER = f"{DEDUPLICATION_SET}__{GROUP_REFERENCE_PK}"

ENCODING = "image"
ENCODING_LIST = f"{ENCODING}s"

BULK = "bulk"
BULK_ENCODING = f"{ENCODING}_{BULK}"
BULK_ENCODING_LIST = f"{ENCODING_LIST}_{BULK}"

DUPLICATE = "duplicate"
DUPLICATE_LIST = f"{DUPLICATE}s"

IGNORED = "ignored"
REFERENCE_PK = "reference_pk"
FILENAME = "filename"
IGNORED_REFERENCE_PK_LIST = f"{IGNORED}/{REFERENCE_PK}s"
IGNORED_FILENAME_LIST = f"{IGNORED}/{FILENAME}s"
