title: "HOPE-dD Engine"
description: "HOPE deduplication engine documentaion"
theme: "just-the-docs"
favicon_ico: "/assets/images/favicon.ico"

url: https://vitali-yanushchyk-valor.github.io/hde-doc/

aux_links:
  HOPE Repository: https://github.com/unicef/hct-mis
  HOPE-DE Repository: https://github.com/unicef/hope-dedup-engine

# Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
mermaid:
  version: "10.9.1"

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Color scheme supports "light" (default) and "dark"
# color_scheme: dark


# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# ga_tracking: 
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)



# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2024-2024. Distributed by ..."

# Footer last edited timestamp
# last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
# last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
