name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    if: vars.DEFAULT_PROJECT
    runs-on: ubuntu-latest
    name: Assign to Project
    steps:
    - name: Assign NEW issues and NEW pull requests to '${{ vars.DEFAULT_PROJECT }}'
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: ${{ vars.DEFAULT_PROJECT }}
      with:
        project: ${{ vars.DEFAULT_PROJECT }}
        column_name: 'New'
