name: CI

on: always

env:
  DOCKER_DEFAULT_PLATFORM: linux/amd64
  DOCKER_CACHE_IMAGE: ${{ vars.DOCKERHUB_ORGANIZATION }}/hope-support-images

jobs:

    debug:
      runs-on: ubuntu-20.04
      if: ${{ github.event.act }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Calculate hash
          uses: ./.github/actions/hash
          id: release_hash

        - name: Image name
          id: image_name
          run: |
            image_name="$DOCKER_CACHE_IMAGE:hde-dev-${{ steps.release_hash.outputs.hash }}"
            image_name_latest="$DOCKER_CACHE_IMAGE:hde-dev-latest"
            echo "name=$image_name" >> $GITHUB_OUTPUT
            echo "latest=$image_name_latest" >> $GITHUB_OUTPUT

        - name: Check if image exists
          uses: ./.github/actions/image_exists
          id: image_exists
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            image: ${{ vars.DOCKERHUB_ORGANIZATION }}/hope-support-images
        - name: Dump info
          run: |
            echo "======================================================="
            echo "Name  : ${{steps.image_name.outputs.name}}"
            echo "Hash  : ${{steps.release_hash.outputs.hash}}"
            echo "Exists: ${{steps.image_exists.outputs.exists}}"
            echo "======================================================="
